### ISSUE TITLE
Application for g-up

### ISSUE THREAD

**Issue by Nichokas** [1Password/for-open-source#1006]
### Account URL

teamgup.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [ ] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

g-up

### Short description

G-up is an open-source Rust tool for uploading files to Google Drive from the terminal. It offers a streamlined way to manage cloud storage from the command line, with future updates planned to include additional cloud providers.

### Number of team members/core contributors

1

### Homepage URL

https://github.com/Nichokas/g-up

### License type

MIT

### License URL

https://github.com/Nichokas/g-up/blob/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Nicolas Rodriguez Alvarez

### Email

nicholas.sapu5+g-up@gmail.com

### Project role

Founder or Owner

### Profile or website

https://github.com/Nichokas

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

1Password will be utilized to store keys for Flathub and future distribution methods.

The project is 30 days or more old but on github it´s only 10.

**Comment by Nichokas** [comment]
* renamed to https://github.com/Nichokas/g_up

**Comment by Nichokas** [comment]
@jodyheavener  Sorry to bother you but is this
 normal?

![IMG_9886](https://github.com/user-attachments/assets/ea8f4832-d05e-496f-9b66-3867e185a8c2)

**Comment by jodyheavener** [comment]
Hey @Nichokas, apologies - this issue should be resolved now. Please let me know if you continue to run into problems here. Thank you!
