### ISSUE TITLE
Application for Python Nordeste

### ISSUE THREAD

**Issue by itepifanio** [1Password/for-open-source#1007]
### Account URL

https://pythonnordeste.1password.com/

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

Python Nordeste

### Short description

Python Nordeste is a non-profit itinerant technology event organized by the community for the community. Held annually since 2013 by the Python programming language enthusiasts in Northeast Brazil, it's a hallmark of regional tech engagement. 

### Number of team members/core contributors

5

### Homepage URL

https://pythonnordeste.org

### Repository URL

https://github.com/pythonNordeste/

### License type

GNU General Public License v3.0

### License URL

https://github.com/pythonNordeste/pyne2018/blob/32946c0d960de49cbf052acd77523346d3df42c3/LICENSE#L4

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Ítalo Epifânio

### Email

italoepifaniols@gmail.com

### Project role

Founder or Owner

### Profile or website

https://github.com/itepifanio/

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @itepifanio, thanks for your application. I am reviewing this application but cannot find the 1Password account with the URL `https://pythonnordeste.1password.com/`. Can you confirm that this team account exists? Thank you!

**Comment by jodyheavener** [comment]
Ah! Apologies, I can see it now. Looks like this application is good to go.
