### ISSUE TITLE
Application for [project name]

### ISSUE THREAD

**Issue by William-HCX** [1Password/for-open-source#1011]
### Account URL

poweredbyloveresponsibilitycoltd.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

myawesomeproject

### Short description

use for my awesome project.

### Number of team members/core contributors

20

### Homepage URL

https://myawesomeproject.org

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

chenxihao

### Email

hcx3630@gmail.com

### Project role

Founder or Owner

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

A short description of what we do.
https://myawesomeproject.org

**Comment by jodyheavener** [comment]
Hi @William-HCX I'm going to close this an incomplete application. If you have an active open source project you're interested in applying with, please open a new application. Thank you.

**Comment by William-HCX** [comment]
Thank you @jodyheavener, where do I fill in the application title?
