### ISSUE TITLE
Application for Lakota Robotics

### ISSUE THREAD

**Issue by reediculous456** [1Password/for-open-source#1015]
### Account URL

lr1038.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Lakota Robotics

### Short description

Lakota Robotics is a community-based FIRST Robotics team with the mission of inspiring our students (grades 7-12) to pursue careers in science, engineering, and technology. We equip them to become confident and responsible citizens to make meaningful contributions to the world.

### Number of team members/core contributors

75

### Homepage URL

https://lakotarobotics.org

### Repository URL

https://github.com/LakotaRobotics1038/2024RobotProject

### License type

Custom

### License URL

https://github.com/LakotaRobotics1038/2024RobotProject/blob/main/WPILib-License.md

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Wesley Reed

### Email

wes@lakotarobotics.org

### Project role

Organizer or Admin

### Profile or website

https://github.com/reediculous456

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

Lakota Robotics is a [FIRST Robotics Team](https://www.firstinspires.org/robotics/frc) that is dedicated to open source STEM. We participate in a group of teams called [The Open Alliance](https://www.theopenalliance.com/) where we share our code, CAD designs, and design processes public and documented to help other teams with their own projects.
We offer our program free of charge to all students grades 7-12 in our community and represent 12 different high schools in the area. All of our annual budget comes from sponsors, grants, and donations. We also do lots of [community outreach](https://lakotarobotics.org/outreach/community/) including [holding robotics camps](https://lakotarobotics.org/outreach/workshops/) for the local Girl Scouts of America troops to further STEM education in our community

**Comment by jodyheavener** [comment]
Hey @reediculous456, thanks for your application. I'll need to gather some more information from you; if you don't mind sending an email to opensource@1password.com with a reference to this page, we can proceed from there. Thank you!
