### ISSUE TITLE
Application for etcd

### ISSUE THREAD

**Issue by ahrtr** [1Password/for-open-source#1016]
### Account URL

https://team-etcd.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

etcd

### Short description

etcd is a distributed reliable key-value store for the most critical data of a distributed system.

### Number of team members/core contributors

4

### Homepage URL

https://etcd.io/

### Repository URL

https://github.com/etcd-io/etcd

### License type

Apache License Version 2.0

### License URL

https://github.com/etcd-io/etcd/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Benjamin Wang

### Email

benjamin.ahrtr@gmail.com

### Project role

Core Maintainer

### Profile or website

https://github.com/kubernetes/community/tree/master/sig-etcd#technical-leads

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by ahrtr** [comment]
Hello,

How can I change the team name to `etcd` and account URL to `https://team-etcd.1password.com/`? 

Thanks,

**Comment by jodyheavener** [comment]
Hi @ahrtr, thanks for your application. I see you have indicated that this application is for both a team and an event. Can you provide a little more information about this? Thank you.

**Comment by ahrtr** [comment]
> Hi @ahrtr, thanks for your application. I see you have indicated that this application is for both a team and an event. Can you provide a little more information about this? Thank you.

Sorry for the confusion. We will only use 1password to manage some credentials for now. So I guess that it should be only for a team?

**Comment by jodyheavener** [comment]
> > Hi @ahrtr, thanks for your application. I see you have indicated that this application is for both a team and an event. Can you provide a little more information about this? Thank you.
> 
> Sorry for the confusion. We will only use 1password to manage some credentials for etcd (i.e. the password for image registry) for now. So I guess that it should be only for a team?

That sounds good to me - if you'd like to update the application I can take another pass!

**Comment by ahrtr** [comment]
> That sounds good to me - if you'd like to update the application I can take another pass!

Updated.

**Comment by ahrtr** [comment]
Thank you @jodyheavener
