### ISSUE TITLE
Application for [Custom ESXi ISO images]

### ISSUE THREAD

**Issue by nvphuy** [1Password/for-open-source#1025]
### Account URL

nvphuy.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Custom ESXi ISO images

### Short description

custom ESXi ISO images with additional network drivers

### Number of team members/core contributors

1

### Homepage URL

https://github.com/nvphuy/custom-esxi-iso-with-network-drivers

### Repository URL

https://github.com/nvphuy/custom-esxi-iso-with-network-drivers

### License type

MIT

### License URL

https://github.com/nvphuy/custom-esxi-iso-with-network-drivers/blob/main/LICENSE.txt

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Huy Nguyen

### Email

nvp.huy@gmail.com

### Project role

Founder or Owner

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @nvphuy, thanks for your application. This program is typically intended for open source projects that are actively being worked on. It doesn't appear that there has been much activity in the project you've listed. Is there anything else you can provide to demonstrate active development? Thanks!

**Comment by nvphuy** [comment]
Hi @jodyheavener, I apologize for the prolonged neglect of this project. I am committed to making numerous updates in the near future. Currently, I am reviving it with a renewed and positive direction, and I hope you will give it another consideration.
