### ISSUE TITLE
Application for [XtPlayer]

### ISSUE THREAD

**Issue by Achieve777** [1Password/for-open-source#1028]
### Account URL

https://balrogs.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

XtPlayer

### Short description

An HTML5 player supporting Danmaku (bullet comments) and subtitles (dev)

### Number of team members/core contributors

2

### Homepage URL

https://github.com/Achieve777/XtPlayer

### Repository URL

https://github.com/Achieve777/XtPlayer

### License type

Apache License 2.0

### License URL

https://github.com/Achieve777/XtPlayer/blob/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Apache L 

### Email

apache777@foxmail.com

### Project role

Founder or Owner

### Can we contact you?

- [X] Yes, you may contact me

**Comment by SadeQuin50** [comment]
i am being hostage of my own life , francisco quinones 936-966-9361
frankquinones50@icloud.com
1201 avenue e
hunstville tx

they changes my social and bank accouts. i am hours from just killing myself

**Comment by SadeQuin50** [comment]
Please help me
