### ISSUE TITLE
Application for [ScalaMatsuri]

### ISSUE THREAD

**Issue by tomoco95** [1Password/for-open-source#1030]
### Account URL

japanscalaassociation.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [ ] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

ScalaMatsuri

### Short description

The largest international Scala conference in Asia. We plan to hold it in the summer of 2025. 

### Number of team members/core contributors

30

### Homepage URL

https://scalamatsuri.org/

### Repository URL

https://github.com/scalamatsuri/2024.scalamatsuri.org

### License type

None

### License URL

None

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Shoma Nishitateno

### Email

shomatan@scalamatsuri.org

### Project role

Organizer or Admin

### Profile or website

https://scalamatsuri.org/  https://scalajp.github.io/jsa/

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @tomoco95, thanks for your application. Since this is for an event and not a specific project, can you confirm for me that this event is not for profit, and that the account will be used exclusively for the event itself? Thank you!

**Comment by shomatan** [comment]
Hi @jodyheavener , thank you for your prompt response to our application.

Japan Scala Association is a non-profit organization in Japan, as stated in our articles of association. Our primary goal is to foster the Scala community by promoting knowledge sharing and educational activities related to Scala.

ScalaMatsuri is an event dedicated to contributing to the growth of the Scala community. While we do charge a fee to attend, all proceeds are directly invested into the event's operations and supporting the Scala community, such as contributing to open-source Scala projects. Our aim is to foster the overall growth of the Scala community, not for profit.

We also hold a TechSoup account, which further attests to our status as a non-profit organization.

Thank you 🙇

**Comment by tomoco95** [comment]
Hi @jodyheavener , thank you for your prompt response to our application.

Japan Scala Association is a non-profit organization in Japan, as stated in our articles of association. Our primary goal is to foster the Scala community by promoting knowledge sharing and educational activities related to Scala.

ScalaMatsuri is an event dedicated to contributing to the growth of the Scala community. While we do charge a fee to attend, all proceeds are directly invested into the event's operations and supporting the Scala community, such as contributing to open-source Scala projects. Our aim is to foster the overall growth of the Scala community, not for profit.

We also hold a TechSoup account, which further attests to our status as a non-profit organization.

Thank you!
