### ISSUE TITLE
Application for makeroanoke

### ISSUE THREAD

**Issue by ecks** [1Password/for-open-source#1041]
### Account URL

makeroanoke.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

MAKE Roanoke

### Short description

MAKE Roanoke is a non-profit organization dedicated to establishing a community makerspace in Roanoke, VA. MAKE Roanoke is run by volunteers.

MAKE Roanoke exists to promote knowledge, skill, and creativity in science, technology, crafts, and the arts. We strive to foster these values in an inclusive and safe environment. To these ends, MAKE Roanoke provides the following:
* An inclusive and collegial social framework for members to inspire and collaborate with others of similar interests
* A maintained communal space providing safe access to tools and supplies for projects
* Events to promote education and collaboration between members and the greater Roanoke community.

### Number of team members/core contributors

15-20

### Homepage URL

https://www.meetup.com/make-roanoke/

### Repository URL

https://github.com/MAKEroanoke

### License type

GNU

### License URL

https://github.com/MAKEroanoke/makeroanoke.org/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Hristo Asenov

### Email

hristo@makeroanoke.org

### Project role

Organizer or Admin

### Profile or website

https://github.com/ecks

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

As a 501(c)(3) non-profit, we organize meetings and STEM events in the Roanoke, VA area. Additionally, we are in the beginning stages of starting a makerspace.

**Comment by jodyheavener** [comment]
Hey @ecks, appreciate you opening this application! Upon review, your initiative/project doesn't quite appear to be applicable to this program; we typically try to reserve space here for more explicitly open source code bases or events. That being said, as you've indicated you're part of a non-profit, I'd encourage you to reach out to our [1Password for Non-Profits](https://1password.com/for-non-profits/) program. Really appreciate your interest here - please let me know if you have any questions.
