### ISSUE TITLE
Application for icons_plus

### ISSUE THREAD

**Issue by chouhan-rahul** [1Password/for-open-source#965]
### Account URL

codebrine.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [x] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Icons Plus

### Short description

Icons Plus is a package for Flutter developers that provides a collection of attractive icons from different packs. Developers can use this package to quickly and easily find and add icons to their apps. Icons Plus gives developers access to a variety of design elements that can make their apps look more appealing and modern. Developers can also choose from many popular icon packs to suit their preferences and needs.

### Number of team members/core contributors

1

### Homepage URL

https://github.com/chouhan-rahul/icons_plus

### Repository URL

https://github.com/chouhan-rahul/icons_plus

### License type

MIT

### License URL

https://github.com/chouhan-rahul/icons_plus/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Rahul Chouhan

### Email

rahul-chouhan@outlook.com

### Project role

Founder or Owner

### Profile or website

https://github.com/chouhan-rahul

### Can we contact you?

- [X] Yes, you may contact me

**Comment by chouhan-rahul** [comment]
Thank you for your response. I apologize for any confusion. I intended to convey that both my team and I will be utilizing the 1Password account to ensure secure management of our credentials for the upcoming event.

**Comment by chouhan-rahul** [comment]
> Hey @chouhan-rahul, thanks for your application. It looks like you indicated that this is for both a team and an event. Could you tell me more about the team and the event this is for? I'm not sure if I am understanding based on the application. Thank you!

Thank you for your response. I apologize for any confusion. I intended to convey that both my team and I will be utilizing the 1Password account to ensure secure management of our credentials for the upcoming event.

**Comment by jodyheavener** [comment]
Hi there @chouhan-rahul, I have some additional questions about your application. Please send me an email (opensource@1password.com) and I would be happy to discuss further. Thank you!

**Comment by chouhan-rahul** [comment]
> Hi there @chouhan-rahul, I have some additional questions about your application. Please send me an email (opensource@1password.com) and I would be happy to discuss further. Thank you!

I've sent an email please check.
