### ISSUE TITLE
Application for Salesforce-Integration

### ISSUE THREAD

**Issue by raphaelgwx** [1Password/for-open-source#968]
### Account URL

raphaelgwx.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

Salesforce teamwork project

### Short description

Salesforce teamwork project which may contain some integration, backend and frontend developments.

### Number of team members/core contributors

5

### Homepage URL

https://github.com/Salesforce-RaphaelG/Integration-SuperBadge

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Wenxuan Gong

### Email

raphaelgwx@163.com

### Project role

Founder or Owner

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @raphaelgwx, thanks for your application. Upon review there appears to be a handful of issues with your application:

- You have indicated that this application is for both a team and an event, however the linked repository appears to be a single project. Can you clarify what you intend to use this account for?
- Your listed repository does not contain a LICENSE. We require a permissive open source license be part of the repository you're applying with.
- Your repository appears to be inactive. We provide free accounts to support open source projects that are actively being maintained.

For these reasons I believe this program may not be a good fit for your project. If you would like to re-apply, please review the [Requirements](https://github.com/1Password/for-open-source?tab=readme-ov-file#-requirements) and open a new application issue. Thank you!
