### ISSUE TITLE
Application for Black Python Devs

### ISSUE THREAD

**Issue by kjaymiller** [1Password/for-open-source#970]
### Account URL

https://blackpythondevs.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Black Python Devs

### Short description

Black Python Devs is a non-profit focused on building more Black and Colo(u)red Pythonistas around the world.

We have many projects to help Black led orgs and other affinity groups to grow.

### Number of team members/core contributors

5

### Homepage URL

https://blackpythondevs.com

### Repository URL

https://github.com/blackpythondevs/.maintainers

### License type

MIT

### License URL

https://github.com/BlackPythonDevs/.github/blob/main/LICENSE.md

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Kevin J Miller

### Email

leadership@blackpythondevs.com

### Project role

Founder or Owner

### Profile or website

https://kjaymiller.com

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hey @kjaymiller, thanks for applying! It looks like the email provided does belong to the account you're applying with. If you're able to update your application to reflect an email associated with `blackpythondevs.1password.com` I can take another look. If you're unable to provide it, please shoot me an email: opensource@1password.com. Thank you!

**Comment by kjaymiller** [comment]
I've updated the email to leadership@blackpythondevs.com
