### ISSUE TITLE
Application for go-httpwrapper

### ISSUE THREAD

**Issue by bugVanisher** [1Password/for-open-source#975]
### Account URL

bugger.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [] Yes, this application is for an event

### Project name

go-httpwrapper

### Short description

Go http wrapper for boomer, this project is born for codeless load test experience in http protocol based on boomer - the real load generator

### Number of team members/core contributors

2

### Homepage URL

https://github.com/bugVanisher/go-httpwrapper

### Repository URL

https://github.com/bugVanisher/go-httpwrapper

### License type

MIT

### License URL

https://github.com/bugVanisher/go-httpwrapper/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

bugvanisher

### Email

gannicus_yu@163.com

### Project role

Founder or Owner

### Profile or website

https://bugvanisher.cn/

### Can we contact you?

- [ ] Yes, you may contact me

### Additional comments

Thank you for your attention

**Comment by jodyheavener** [comment]
Hi @bugVanisher, thanks for your application. It looks like you've indicated that this application is for both a team and an event. Can you tell me more about this? Thank you!

**Comment by bugVanisher** [comment]
Hi @jodyheavener , I think I have misunderstood the meaning of "Event application", this application is for a team to open source code which make it easier to use another open source application "boomer". I really appreciate your giving back to the open source community, we like the open source community and  want to make more contributions to it in other open source applications, the 1password will help us a lot, thank you
