### ISSUE TITLE
Application for obsidian-clipper

### ISSUE THREAD

**Issue by Ruoyu-Klaus** [1Password/for-open-source#976]
### Account URL

https://klauswang.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

obsidian-clipper

### Short description

A browser extension: Easy to clip web content and paste into your obsidian vault

### Number of team members/core contributors

2

### Homepage URL

https://github.com/Ruoyu-Klaus/obsidian-clipper

### Repository URL

https://github.com/Ruoyu-Klaus/obsidian-clipper

### License type

MIT

### License URL

https://github.com/Ruoyu-Klaus/obsidian-clipper/blob/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Ruoyu

### Email

klaus1201810802@gmail.com

### Project role

Founder or Owner

### Profile or website

https://github.com/Ruoyu-Klaus

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @Ruoyu-Klaus, sorry for the confusion. I think I forgot to apply the promotion to your account. This should be complete now. To avoid duplicate data I'm going to close this issue, but please feel free to comment as needed. Sorry about that!

**Comment by Ruoyu-Klaus** [comment]
Hi @jodyheavener,  no problem at all, glad it's sorted. I appreciate you taking care of it!
