### ISSUE TITLE
Application for VectorHub

### ISSUE THREAD

**Issue by guangzhengli** [1Password/for-open-source#980]
### Account URL

vectorhub.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

VectorHub ChatFiles

### Short description

Out team need 1password to share the aws & vercel & cloudflare secret 

### Number of team members/core contributors

5

### Homepage URL

https://chatfile.vectorhub.org/

### Repository URL

https://github.com/guangzhengli/ChatFiles

### License type

MIT

### License URL

https://github.com/guangzhengli/ChatFiles/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Guangzheng Li

### Email

iguangzhengli@gmail.com

### Project role

Founder or Owner

### Profile or website

https://x.com/iguangzhengli

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @guangzhengli, thanks for your application. It looks like you've indicated that this application is for both a team and an event. Can you tell me more about this? Thank you!

**Comment by guangzhengli** [comment]
Hi @jodyheavener, thanks for you response,  It is for a team.

**Comment by jodyheavener** [comment]
Hi @guangzhengli, thanks for your update. One of the requirements for 1Password for Open Source is that the project or team must not be associated with commercial activity. You can see the [full requirements here](https://github.com/1Password/for-open-source#-requirements).

It appears the account you are applying with could be used to support the commercial end of VectorHub, as a pricing page [exists here](https://vectorhub.org/#pricing). Based on this your account would not qualify for this program.

If this assessment feels incorrect, and you are able to clearly distinguish between the open source work and commercial work, let me know and I can take another look.

**Comment by guangzhengli** [comment]
Ok,Thanks
