### ISSUE TITLE
Application for Grails Foundation

### ISSUE THREAD

**Issue by bdavis2222** [1Password/for-open-source#985]
### Account URL

https://team-grailsfoundation.1password.com/

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Grails

### Short description

Grails is a web application framework based on Groovy for Java Virtual Machine with a Spring Boot foundation.

### Number of team members/core contributors

19

### Homepage URL

https://grails.org/

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Bradley Davis

### Email

itadmin@objectcomputing.com

### Project role

Founder or Owner

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hey @bdavis2222 thanks for your application. I'm unable to verify that you're associated with the Grails foundation and there is an additional [application for Grails](https://github.com/1Password/for-open-source/pull/433) from a few years ago. Could you provide some more information about your work with the foundation? Thank you.

**Comment by bdavis2222** [comment]
The request at https://github.com/1Password/for-open-source/pull/433 was
approved.  That request was submitted by Sergio del Amo Caballero who is on
our team.  In the time since then there were some organizational changes
and we didn't need that environment so it was closed down.  In the time
since it was closed down, the group has decided that it does need its own
separate 1Password environment as initially planned.  When we initiated the
more recent request at
https://github.com/1Password/for-open-source/issues/985, because of some
internal communication gaps at our end, not everyone involved here knew we
had the other environment at one point, or I would have called that out in
the second request.  I really am sorry about the confusion.

If we can resurrect the old environment I think that will work.  If it is
better to establish a new environment, that works great as well.  We really
appreciate the OSS support from 1Password and appreciate your guidance for
how best to move forward.

If you need verification from Sergio that we are all working together on
the same team here I can ask him to send you an email, or he could leave a
comment in either of the PRs mentioned above.  Please let us know whatever
we can do to help with clarity.

Thank you!
Bradley Davis

**Comment by sdelamo** [comment]
I deleted [grailsfoundation.1password.com.](https://grailsfoundation.1password.com/) That is why we need to create a new one again.
