### ISSUE TITLE
Application for WebhookDLL

### ISSUE THREAD

**Issue by ThemanRonin** [1Password/for-open-source#986]
### Account URL

nnametechnologycoltd.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [ ] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

WebhookDLL

### Short description

A DLL created based on the WeCom webhook for enterprises, making it convenient to directly invoke in programs.

### Number of team members/core contributors

1

### Homepage URL

https://github.com/ThemanRonin/Webhook_DLL 

### Repository URL

https://github.com/ThemanRonin/Webhook_DLL 

### License type

MIT

### License URL

https://github.com/ThemanRonin/Webhook_DLL/blob/main/LICENSE.txt

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

ThemanRonin

### Email

themanronin@gmail.com

### Project role

Founder or Owner

### Profile or website

https://github.com/ThemanRonin/

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hi @ThemanRonin, thanks your application! One of our requirements for the program is that project be at least 30 days old to help determine if it is an active open source project. Looking at the repository you submitted, it appears that commits only span a couple days. This can be the case when you are working on it locally and then want to put it all up on GitHub so you create your first commit, but it's hard for us to make a determination. With this in mind, would you be up for re-applying in about a month's time? This will allow us to see that this project is actively being developed, possibly with more commits. Thank you for understanding.

**Comment by ThemanRonin** [comment]
@jodyheavener 
HI. I apologize for any inconvenience regarding the duration of the project's history. I will reapply in 30 days, and during this period, I will maintain an active engagement with the project by actively submitting code. Thank you for your response.

**Comment by jodyheavener** [comment]
@ThemanRonin Thank you for your response and understanding! I'm gong to close this application for now. After the time has elapsed please feel free to open a new application and I'll happily take a look 😄
