### ISSUE TITLE
Application for BiomeJS

### ISSUE THREAD

**Issue by Conaclos** [1Password/for-open-source#988]
### Account URL

https://team-biomejs.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

BiomeJS

### Short description

Biome is a toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP. 

### Number of team members/core contributors

8

### Homepage URL

https://biomejs.dev/

### Repository URL

https://github.com/biomejs/biome

### License type

MIT and Apache-2.0

### License URL

https://github.com/biomejs/biome/blob/main/LICENSE-MIT

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Victorien Elvinger

### Email

victorien@elvinger.fr

### Project role

Founder or Owner

### Profile or website

https://github.com/Conaclos

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Love Biome, happy to have you in the program!

**Comment by Conaclos** [comment]
@jodyheavener

Thanks :)

We previously subscribed to a 1 year family plan.
Do you know if it is possible to easily export the passwords from a family account to a team account?
Also, is it possible to cancel the family plan and get (partial) refund?

**Comment by jodyheavener** [comment]
Hey @Conaclos! Thanks for the question. If you're signed in to both accounts on desktop it's easy to copy/move items from one account to another, check out [this article](https://support.1password.com/move-copy-items/). You can also manually [export](https://support.1password.com/export/) and [re-import](https://support.1password.com/import/#import-a-1password-unencrypted-export-1pux-file) your items from one account to another. For billing and refund inquiries, I'd recommend directing questions to support@1password.com who will be able to help you out.
