### ISSUE TITLE
Flipping Game Tutorial

### ISSUE THREAD

**Issue by khanhdew** [1Password/for-open-source#994]
### Account URL

keplar-team.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [X] Yes, this application is for an event

### Project name

Flipping Game Tutorial

### Short description

An java game for begin java developer

### Number of team members/core contributors

2

### Homepage URL

https://github.com/khanhdew/FlippingGame

### Repository URL

https://github.com/khanhdew/FlippingGame

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Khanh Nguyen

### Email

khanhdeptrai292004@gmail.com

### Project role

Founder or Owner

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
@khanhdew Thanks for your application! It appears you have indicated that this application is for both a team and an event. Can you tell me more? I also don't see a LICENSE file in your project. Finally, is this a project that is actively being worked on? Thank you!

**Comment by khanhdew** [comment]
Hello @jodyheavener and 1Password team,
Thanks for reaching out  with my application,
First, I can confirm that the application is for both a team and an event. My propose to create this repository is for the begining Java developers can take it as an example for them to build their first game base on "piece-game"( mine is Flipping Game).
Second, I've recently added a LICENSE to the  repository as your  suggestion. I'm using GNU LICENSE to my project. I'm still planning on the project to add new features so that my visistors can base on that and build  their own.
