### ISSUE TITLE
Application for Obscreen

### ISSUE THREAD

**Issue by jr-k** [1Password/for-open-source#995]
### Account URL

obscreen.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Obscreen

### Short description

Obscreen turns any screen into a digital sign by offering simple software with few dependencies. Obscreen allows you to manage digital signs on a large scale, enabling you to update and schedule content, monitor screens, and display content from your existing technology infrastructure.

### Number of team members/core contributors

2

### Homepage URL

https://obscreen.io

### Repository URL

https://obscreen.io

### License type

GPLv2

### License URL

https://github.com/jr-k/obscreen/blob/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Jessym

### Email

jessym.reziga@gmail.com

### Project role

Founder or Owner

### Profile or website

https://github.com/jr-k

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

No, thanks !

**Comment by jodyheavener** [comment]
Hi @jr-k, thanks for your application. I can't seem to locate your 1Password account from the information provided. Could you please let me know if the account URL and/or email you've provided is for an active 1Password account? If you'd prefer, you can also email opensource@1password.com to provide information.

**Comment by jr-k** [comment]
Oh, sorry. I thought you would create it for the occasion with the information I provided here. I just created an account with the same email address mentioned in my PR, does that work for you?

**Comment by jr-k** [comment]
@jodyheavener done
