### ISSUE TITLE
Application for "LF Broadband"

### ISSUE THREAD

**Issue by joey-onf** [1Password/for-open-source#996]
### Account URL

https://lfbroadband.1password.com 

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

LF Broadband

### Short description

    VOLTHA is an open source project for PON broadband access equipment, supporting the principle of multi-vendor, disaggregated, “any broadband access as a service” for the Central Office. VOLTHA provides isolation between an abstract (vendor agnostic) PON management system, and a set of vendor-specific and white-box PON hardware devices.

On its north-bound interface, VOLTHA provides a set of abstract APIs that enable the PON network to appear as a programmable Ethernet switch to an SDN controller.  On its south-bound side, VOLTHA communicates with PON hardware devices using vendor-specific protocols through OLT and ONU adapters.

VOLTHA is in production with major operators, including Deutsche Telekom, Turk Telekom, and Reliance Jio.

### Number of team members/core contributors

20+

### Homepage URL

https://wiki.lfbroadband.org/pages/viewpage.action?spaceKey=HOME&title=VOLTHA , https://docs.voltha.org , https://www.youtube.com/channel/UCu543KEGcZWICwBjJeymCUw

### Repository URL

https://gerrit.opencord.org/plugins/gitiles/voltha-protos , https://gerrit.opencord.org/plugins/gitiles/voltha-go , https://gerrit.opencord.org/plugins/gitiles/voltha-openolt-adapter

### License type

Apache-2.0, MIT-2.0

### License URL

https://gerrit.opencord.org/plugins/gitiles/voltha-protos/+/refs/heads/master/LICENSE , https://gerrit.opencord.org/plugins/gitiles/voltha-lib-go/+/refs/heads/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

LF Broadband

### Email

releng+broadband@linuxfoundation.org

### Project role

Team Member or Employee

### Profile or website

https://www.linuxfoundation.org/

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

OSS Project VOLTHA initially started out as an Open Networking Foundation project:

- https://opennetworking.org/voltha/

ONF later merged with The Linux Foundation, the project is now named "LF Broadband"

- https://www.linuxfoundation.org/press/onf-merges-market-leading-portfolio-of-networking-projects-into-linux-foundation

**Comment by jodyheavener** [comment]
Hi @joey-onf, thanks for your application. I can't seem to locate your 1Password account from the information provided. Could you please let me know if the account URL and/or email you've provided is for an active 1Password account? If you'd prefer, you can also email [opensource@1password.com](mailto:opensource@1password.com) to provide information.

**Comment by joey-onf** [comment]
Hi Jody,

Whups, too many accounts in play and this github checkin/email is attached
to my ONF account :)
The email address I registered with 1password is:
***@***.***

Let me know if you have any other questions -- Joey

**Comment by jodyheavener** [comment]
Hey @joey-onf, thanks for following up. I believe GitHub might have masked the email in your response. If you'd like, feel free to reach out to me at opensource@1password.com and I can help sort out your account. Thanks!

**Comment by joey-onf** [comment]
Hi Jody,

A little while back you helped me with activating a new account/vault for
the LF Broadband account.
A 14-day trial account was created, request was processed all was good.
Until recently the account & credentials have been usable w/o issue.

https://lf-broadband.1password.com

Checking account status today in the desktop client I see it is listed as
"Account Frozen".

From the account/vault process I am aware of so far:

   - Linux Foundation projects normally have an OSS "free coupon" attached
   to an account.
   - Coupon is attached, trial account is allowed to expire, the OSS coupon
   becomes activate at that time preventing the account from being deactivated.


Might anything still be needed to continue using the project account ?
If there is a coupon attached to this account any chance it may be expired
or not appropriate to the account it was attached to ?

Thanks -- Joey

Joey Armstrong
The Linux Foundation
***@***.***
New York (EST)

**Comment by jodyheavener** [comment]
Hi @joey-onf, sorry for the confusion. Your account should be unblocked now. Please let me know if you continue to experience any issues.
