### ISSUE TITLE
Application for Mastodon

### ISSUE THREAD

**Issue by timetinytim** [1Password/for-open-source#997]
### Account URL

https://mastodon.1password.com/

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Mastodon

### Short description

Mastodon is a free, open-source social network server based on ActivityPub where users can follow friends and discover new ones. All Mastodon servers are interoperable as a federated network.

### Number of team members/core contributors

10

### Homepage URL

https://joinmastodon.org/

### Repository URL

https://github.com/mastodon/mastodon

### License type

AGPL v3

### License URL

https://github.com/mastodon/mastodon/blob/main/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Timothy Campbell

### Email

tim@joinmastodon.org

### Project role

Team Member or Employee

### Profile or website

https://www.linkedin.com/in/timothy-campbell-222a8438/

### Can we contact you?

- [X] Yes, you may contact me

### Additional comments

I'm currently working with Mastodon as the lead DevOps engineer managing all the infrastructure for our official instances, our deployment strategies and helm charts, and our IT infrastructure, which includes our password managers. Most of my own contributions have been to our internal kubernetes deployments, our [helm chart](https://github.com/mastodon/chart) (which we will be renovating shortly) as well as various terraform modules located in our github, all of which are open source. We have been using 1password for employee passwords, as well as various server credentials, API keys and so on, and have plans to use the 1password kubernetes operator to sync keys in 1password with our kubernetes secrets.

Our core team is quite small, but we've been able to add some new contributors thanks to additional funding, and would love to keep utilizing 1password as our manager for these new team members as well.

**Comment by jodyheavener** [comment]
Welcome to the program, Mastodon! 🎉
